# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: xentra-ecommerce-prueba
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
#frameworkVersion: '1.53.0'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-east-1


functions:
    auth:
      handler: index.handler
      events:
       - http: GET auth
         cors:
            origin: '*'
            cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate'
            headers: '*'
       - http: OPTIONS auth
         cors:
            origin: '*'
            cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate'
            headers: '*'
    productos:
      handler: index.handler
      events:
       - http: GET productos
         cors: true
    productos-marca-subcategoria:
      handler: index.handler
      events:
       - http: POST productos/marcas/{marca}/{subcategoria}
         cors:
            origin: '*'
            cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate'
            headers: '*'
       - http: OPTIONS productos/marcas/{marca}/{subcategoria}
         cors:
            origin: '*'
            cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate'
            headers: '*'
    productos-relacionados:
      handler: index.handler
      events:
       - http: GET productos/relacionados
         cors:
            origin: '*'
            cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate'
            headers: '*'
       - http: OPTIONS productos/relacionados
         cors:
            origin: '*'
            cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate'
            headers: '*'
    productos-scat_detacada:
      handler: index.handler
      events:
       - http: POST productos/scat_detacada
         cors:
            origin: '*'
            cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate'
            headers: '*'
       - http: OPTIONS productos/scat_detacada
         cors:
            origin: '*'
            cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate'
            headers: '*'
    producto:
      handler: index.handler
      events:
       - http: GET producto
         cors: true
    diseno-config:
      handler: index.handler
      events:
       - http: GET diseno/configuraciones
         cors:
            origin: '*'
            cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate'
            headers: '*'
       - http: OPTIONS diseno/configuraciones
         cors:
            origin: '*'
            cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate'
            headers: '*'
    marcas:
      handler: index.handler
      events:
       - http: GET marcas
         cors: true
         accessConfigurations:
            vpcSubnet:
              - subnet-03dbd1c1959f6e946
              - subnet-0acd93629e01b1f83
            vpcSecurityGroup: sg-0b69b5acd6759b172
