# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: api-xentra
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
#frameworkVersion: '1.53.0'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-east-1


functions:
    productos:
      handler: index.handler
      events:
       - http: GET productos
    productos-filtros:
      handler: index.handler
      events:
       - http: GET productos/filtros
    productos-filtros-get:
      handler: index.handler
      events:
       - http: POST productos/filtros2
    producto:
      handler: index.handler
      events:
        - http: GET producto
    marcas:
      handler: index.handler
      events:
        - http: GET marcas
